### PR TITLE
Made it work on python3

### PR DESCRIPTION
**Pull request by willnaoosmith**

### CODE REVIEW

**Comment by Suleman-Elahi** [comment]
Why did I get email notification for this? I have no relation to this repository?

**Comment by willnaoosmith** [comment]
No idea.
You're not on the list of the people who watch this repository.
Didn't fork it.
Didn't contribute to it.

You should not receive any emails about it.

**Comment by Suleman-Elahi** [comment]
So wierd 
image

**Comment by willnaoosmith** [comment]
Yup, really weird.
Looks like there's 2 other people on the mail too.

**Comment by ruped24** [comment]
Nice work guys:
Unfortunately I will not be upgrading _this_ app to Python3 - the code is frozen.
Hence, the [AppImage](https://github.com/ruped24/autovpn2/releases/tag/v1.0) doesn't require _any_ Python .

**Comment by ruped24** [comment]
Nice work guys:
Unfortunately I will not be upgrading this app to Python3 - the code is frozen.
Hence, the [AppImage](https://github.com/ruped24/autovpn2/releases/tag/v1.0) doesn't require any Python .

**Pull request closed without merging**
